apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-log-config
  namespace: {{ .Release.Namespace }}
data:
  log_config.yaml: |-
    {{- .Files.Get "config/log_config.yaml" | nindent 4 }}
---